version: '3'
services:
  strapi-db:
    image: postgres:14-alpine
    container_name: strapi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - "5433:5432"
    volumes:
      - strapi-data:/var/lib/postgresql/data

volumes:
  strapi-data:
